/**
 * E2E export verification driver.
 *
 * Uses the video generated by e2e-engine-test.ts and exercises the app's real
 * export path (buildExportArgs) against a real ffmpeg:
 *   - installs ffmpeg (BtbN win64-gpl) to C:\MCS-Data\ffmpeg if missing
 *   - builds a Shorts (9:16) export with blur-pad, Japanese text overlay,
 *     fade-out and loudness normalization from the 16:9 source
 *   - runs ffmpeg, asserts exit 0 and verifies output dimensions/fps via ffprobe
 *
 * Run:  node scripts/e2e-export-test.ts
 */
import { spawn } from 'node:child_process'
import { existsSync, mkdirSync, readdirSync, statSync, rmSync, copyFileSync } from 'node:fs'
import { join } from 'node:path'
import { path7za } from '7zip-bin'
import { downloadFile, githubReleaseAsset } from '../src/main/core/downloader.ts'
import { buildExportArgs } from '../src/main/media/exportPlan.ts'
import type { ExportRequest, VideoRecord } from '../src/shared/types.ts'

const DATA = process.env.MCS_DATA ?? 'C:\\MCS-Data'
const FFDIR = join(DATA, 'ffmpeg')
const FFMPEG = join(FFDIR, 'ffmpeg.exe')
const FFPROBE = join(FFDIR, 'ffprobe.exe')
const SRC_DIR = join(DATA, 'work', 'engine-output', 'mcs')
const OUT_DIR = join(DATA, 'exports')

const log = (...a: unknown[]): void => console.log(`[${new Date().toISOString().slice(11, 19)}]`, ...a)

function run(exe: string, args: string[]): Promise<{ code: number; out: string }> {
  return new Promise((resolve, reject) => {
    const p = spawn(exe, args, { windowsHide: true })
    let out = ''
    p.stdout.on('data', (d) => (out += String(d)))
    p.stderr.on('data', (d) => (out += String(d)))
    p.on('error', reject)
    p.on('close', (code) => resolve({ code: code ?? -1, out }))
  })
}

async function installFfmpeg(): Promise<void> {
  if (existsSync(FFMPEG) && existsSync(FFPROBE)) {
    log('ffmpeg already installed')
    return
  }
  const asset =
    (await githubReleaseAsset('BtbN/FFmpeg-Builds', 'latest', /^ffmpeg-n[\d.]+-latest-win64-gpl-[\d.]+\.zip$/)) ??
    (await githubReleaseAsset('BtbN/FFmpeg-Builds', 'latest', /^ffmpeg-master-latest-win64-gpl\.zip$/))
  if (!asset) throw new Error('ffmpeg asset not found')
  log(`downloading ${asset.name} (${(asset.size / 1e6).toFixed(0)} MB, sha256 ${asset.sha256 ? 'yes' : 'NO'})`)
  const archive = join(DATA, 'work', asset.name)
  await downloadFile(
    { id: 'ffmpeg', label: asset.name, url: asset.url, dest: archive, expectedBytes: asset.size, expectedSha256: asset.sha256 ?? undefined },
    (p) => {
      if (p.status !== 'downloading') log(`  ffmpeg: ${p.status}${p.error ? ' ' + p.error : ''}`)
    }
  )
  const tmp = join(DATA, 'work', 'ffmpeg-extract')
  rmSync(tmp, { recursive: true, force: true })
  await new Promise<void>((resolve, reject) => {
    const p = spawn(path7za, ['x', archive, `-o${tmp}`, '-y'], { windowsHide: true })
    p.on('close', (c) => (c === 0 ? resolve() : reject(new Error(`7za exit ${c}`))))
    p.on('error', reject)
  })
  const root = readdirSync(tmp).find((e) => e.toLowerCase().startsWith('ffmpeg'))
  if (!root) throw new Error('unexpected ffmpeg layout')
  mkdirSync(FFDIR, { recursive: true })
  for (const exe of ['ffmpeg.exe', 'ffprobe.exe']) copyFileSync(join(tmp, root, 'bin', exe), join(FFDIR, exe))
  rmSync(tmp, { recursive: true, force: true })
  rmSync(archive, { force: true })
  log('ffmpeg installed')
}

async function probe(path: string): Promise<{ durationSec: number; width: number; height: number; fps: number }> {
  const { code, out } = await run(FFPROBE, ['-v', 'error', '-print_format', 'json', '-show_streams', '-show_format', path])
  if (code !== 0) throw new Error(`ffprobe exit ${code}`)
  const j = JSON.parse(out) as {
    streams?: Array<{ codec_type?: string; width?: number; height?: number; avg_frame_rate?: string }>
    format?: { duration?: string }
  }
  const v = j.streams?.find((s) => s.codec_type === 'video')
  const [n, d] = (v?.avg_frame_rate ?? '0/1').split('/').map(Number)
  return { durationSec: Number(j.format?.duration ?? 0), width: v?.width ?? 0, height: v?.height ?? 0, fps: n && d ? n / d : 0 }
}

async function main(): Promise<void> {
  await installFfmpeg()

  if (!existsSync(SRC_DIR)) throw new Error(`no generated videos at ${SRC_DIR} — run e2e-engine-test.ts first`)
  const mp4s = readdirSync(SRC_DIR).filter((f) => f.endsWith('.mp4'))
  if (mp4s.length === 0) throw new Error('no mp4 found — run e2e-engine-test.ts first')
  const newest = mp4s.map((f) => ({ f, t: statSync(join(SRC_DIR, f)).mtimeMs })).sort((a, b) => b.t - a.t)[0].f
  const srcPath = join(SRC_DIR, newest)
  const meta = await probe(srcPath)
  log(`source: ${newest} (${meta.width}x${meta.height} @${meta.fps.toFixed(1)}fps, ${meta.durationSec.toFixed(1)}s)`)

  const rec: VideoRecord = {
    id: 'e2e',
    filePath: srcPath,
    thumbPath: '',
    family: 'wan22',
    mode: 't2v',
    prompt: 'e2e',
    negative: '',
    seed: 0,
    width: meta.width,
    height: meta.height,
    fps: meta.fps,
    frames: Math.round(meta.durationSec * meta.fps),
    durationSec: meta.durationSec,
    createdAt: Date.now(),
    favorite: false,
    tags: [],
    requestJson: '{}',
    modelLabel: 'e2e'
  }

  const req: ExportRequest = {
    project: {
      clips: [{ videoId: 'e2e', inSec: 0, outSec: 0 }],
      bgm: null,
      narrations: [],
      overlays: [
        {
          text: '海辺の街 — Movie Creator Studio テスト',
          startSec: 0.2,
          endSec: Math.max(1.5, meta.durationSec - 0.2),
          position: 'bottom',
          fontSizePct: 5,
          color: '#ffffff',
          outline: true
        }
      ],
      fadeInSec: 0.3,
      fadeOutSec: 0.5,
      keepClipAudio: false
    },
    presetId: 'shorts',
    aspectMode: 'blurpad',
    smoothInterpolation: false,
    upscale: true,
    loudnessNormalize: true,
    outputName: 'e2e_shorts'
  }

  mkdirSync(OUT_DIR, { recursive: true })
  const outPath = join(OUT_DIR, 'e2e_shorts_test.mp4')
  rmSync(outPath, { force: true })
  const font = ['C:/Windows/Fonts/meiryo.ttc', 'C:/Windows/Fonts/YuGothM.ttc', 'C:/Windows/Fonts/msgothic.ttc'].find((f) => existsSync(f)) ?? null
  log(`font: ${font ?? 'none'}`)
  const built = buildExportArgs(req, new Map([['e2e', rec]]), [false], false, outPath, font)

  log('running ffmpeg export…')
  const r = await run(FFMPEG, ['-hide_banner', '-y', ...built.args])
  if (r.code !== 0) {
    console.error(r.out.slice(-2500))
    throw new Error(`ffmpeg exit ${r.code}`)
  }
  if (!existsSync(outPath)) throw new Error('output missing')
  const out = await probe(outPath)
  log(`output: ${outPath} (${out.width}x${out.height} @${out.fps.toFixed(1)}fps, ${out.durationSec.toFixed(1)}s, ${(statSync(outPath).size / 1e6).toFixed(2)} MB)`)
  if (out.width !== 1080 || out.height !== 1920) throw new Error(`unexpected dims ${out.width}x${out.height}`)
  if (Math.abs(out.fps - 30) > 0.5) throw new Error(`unexpected fps ${out.fps}`)
  log('✅ EXPORT E2E PASS')
}

main().catch((e) => {
  console.error('EXPORT E2E FAILED:', e)
  process.exit(1)
})
